### ISSUE TITLE
Disassembling 6520 code, option "forceaddr off" in the nfo file appears to not work

### ISSUE THREAD

**Issue by phillipeaton** [Arakula/dasmfw#6]
![image](https://user-images.githubusercontent.com/44277038/166840017-e3ba239a-593e-4b9d-bcd1-fea378ef8903.png)

I also tried switching to "forceaddr on", but no difference.

**Comment by Arakula** [comment]
Could you show me the info file snipped, please?
Because ... staring at the code in Dasm6500.cpp:
```
adr_t Dasm650X::DisassembleCode(...) {
...
  case _abs:                            /* absolute                          */
...
    if (forceExtendedAddr && (W & (uint16_t)0xff00) == (uint16_t)dp)
      sparm = ">" + slbl;
    else
      sparm = slbl;
```
should work, in theory.
Also, is "jetpac" something you might give to me for testing or something proprietary you'd rather not see floating around?

**Comment by phillipeaton** [comment]
I will send it to you.

**Comment by phillipeaton** [comment]
Sent to your listed address on GitHub, let me know if you didn't receive it.

**Comment by Arakula** [comment]
I received it, am going to look at it later.

**Comment by Arakula** [comment]
OK, that was a "collateral damage" ...
you had some lines of the format
```option xxx value * comment```
in your info file.
Unfortunately, dasmfw didn't live up to its own documentation in this case and did _not_ interpret everything including and after the asterisk as a comment, but rather tried to interpret ```value * comment``` as the option's new value - and "off * gotcha" is not one of "off" or "on". Oh well ... should be fixed now.

**Comment by phillipeaton** [comment]
I originally copied the 6502 info file from my 6809 project, then hacked it. I assume this fix would affect 6809 disassemblies also? It could actually break things that previously worked if the now correctly parsed switches get reversed. Not a problem if you know about it, but if you don't and then you upgrade, you might wonder what happened. Perhaps worth noting in the version history.

**Comment by Arakula** [comment]
Yes, this affects all disassemblers in dasmfw, so it might be a good idea to double-check.
It's already noted in the version history; I'll detail that in dasmfw.htm, too.
In the next version.

**Comment by Arakula** [comment]
And I might revise that feature a bit ...

In _some_ info file instructions, asterisks are more meaningful than in others.
Imagine a comment line consisting of a row of asterisks with some text in the middle. Something like
```comment 0815 ********* Here be dragons! *****```
for example.

In previous versions - no problem, it was just copied 1:1.
In the current version - out comes an empty line, as the same is interpreted like
```comment 0815```
until you modify it to the rather impracticable
```comment 0815 \*\*\*\*\*\*\*\*\* Here be dragons! \*\*\*\*\*```
... which, unfortunately, causes the backslashes to be emitted in the disassembly as well.

Not a satisfying solution.
I'll think about it and will presumably replace it with something else. Like "if the instruction has a value part that contains free-form text, just copy the line as is; otherwise, cut it at the asterisk." I think that might work better and reduce the possibility of breaking existing info files.

**Comment by phillipeaton** [comment]
I have another comment-related scenario that produces non-optimal output, I'll document it tonight. (It's possible I can work around it with \, which I didn't know about until now.)

**Comment by Arakula** [comment]
Hmmm, I played with it a bit ... in previous versions, the "an asterisk is a comment start" was already implemented anyway ... but _only_ in lines containing free-form text. Hehe, gotcha. This definitely needs more thinking.

**Comment by phillipeaton** [comment]
Actually, if you look in my nfo file, you'll see that the cchar switch line has no "* text description" part, unlike all my other switch lines. I recall this is because it broke the setting when I commented it previously. I assumed that it was a special case, I didn't consider it a bug!

**Comment by phillipeaton** [comment]
I just had to update a comment above, because it contained a naked "\", which then escaped the following character 🤦‍♂️

**Comment by Arakula** [comment]
Hehe, and that's _exactly_ the fringe case I _knew_ would appear sooner or later :-)
OK, I definitely need to modify the logic.

**Comment by phillipeaton** [comment]
By adding data hints to the info file, I managed to get as65 to assemble the disassembled file, but there are differences between the original binary and the recreation. This is not really a surprise for a first run! I will investigate further.

![image](https://user-images.githubusercontent.com/44277038/167031320-e4a7278d-9b40-49de-9b1c-f2e2a0b2e4f1.png)

**Comment by Arakula** [comment]
Thanks for telling me ... as it's still written in dasmfw.htm, the 650X stuff is largely untested, there might still be errors in the disassembly. If you can pinpoint an instruction that generates a different code when re-assembled, please keep me informed.

I've uploaded v0.25 now, see https://github.com/Arakula/dasmfw/releases/tag/v0.25 - it deals with the issue here in a better way, allowing info file lines like ```option cchar \*```, so I'm closing this issue again.

**Comment by phillipeaton** [comment]
> I have another comment-related scenario that produces non-optimal output, I'll document it tonight. (It's possible I can work around it with \\, which I didn't know about until now.)

I recall what it was that I couldn't produce, it's a line of asterisks from the start of a line, i.e. like this:

![image](https://user-images.githubusercontent.com/44277038/167272123-e15714a8-13b2-4ee8-8379-fa7ec010c2b0.png)

The best I could do was: (I could have probably used asterisks instead of dashes)
![image](https://user-images.githubusercontent.com/44277038/167272119-c62d74d2-a300-4936-9c25-8e4f3988f47e.png)

It's non-optimal because there is a space between the first column `;` and the first `-`, not the end of the world...
